language: cpp
env:
 - TOOL="gcc-4.6" # Use gcc-4.6 (currently travis default)
 - TOOL="gcc-4.7" # Use gcc-4.7
#Clang build is currently broken (mis-detected as crosscompile, see S25RTTR-Aux/s25rttr#4 )
# - TOOL="clang" # Use clang
#Crosscompilation is currently being worked on (see S25RTTR-Aux/s25rttr#3 )
# - TOOL="i686-w64-mingw32" # 32bit MinGW
# - TOOL="x86_64-w64-mingw32" # 64bit MinGW
before_install:
 - "mkdir /tmp/logs && export LOGDIR=/tmp/logs"
 - "sudo add-apt-repository -y 'deb http://archive.ubuntu.com/ubuntu/ quantal main universe' > /tmp/logs/apt-output.log && echo 'Okay.'"
 - "echo '' >> $LOGDIR/apt-output.log && sudo apt-get -qq update >> $LOGDIR/apt-output.log && echo 'Okay.'"
 - "echo '' >> $LOGDIR/apt-output.log && sudo apt-get -qq install libminiupnpc-dev liblua5.2-dev libsdl1.2-dev libsdl-mixer1.2-dev >> $LOGDIR/apt-output.log && echo 'Okay.'"
 - "[ $TOOL = clang ] && echo 'Using clang' && export CXX=clang++ && export CC=clang || true"
 - "[ $TOOL = gcc-4.7 ] && echo 'Using GCC-4.7' && echo '' >> $LOGDIR/apt-output.log && sudo apt-get -qq install g++ g++-4.7 >> $LOGDIR/apt-output.log && export CXX=g++-4.7 && export CC=gcc-4.7 && c++ --version || true"

#The "||true" at the end of some of the commands above makes sure that the build continues even if some of the lines fail (in which case they *would* return false, which *would* abort the build)
script: 
 - cd build 
 - cmake -DCMAKE_INSTALL_PREFIX=/tmp/siedler .. 
 - make all install
after_script:
#tar the logs and upload them to omploader; comment out the line below to disable that
 - "cd /tmp && tar czf logs.tar.gz logs/ && wget -q ompldr.org/ompload && echo 'Downloading ompload script successful.' && chmod +x ompload && ./ompload logs.tar.gz"

notifications:
  irc: "irc.freenode.net#s25rttr-aux"

branches:
  except:
   - bazaar-integration
